language: node_js
sudo: false
node_js:
  - 'node'
before_install:
  - rvm install 2.6.5
notifications:
  email:
  - ogataken@gmail.com
after_success:
- bin/build.sh
deploy:
  provider: releases
  api_key:
    secure: "koqvxEyuSx98G66ymV2UvV2PvH8/N8q+lpnBNUx/jFeIK3gfzst6hvw0d4Q49gJ/5zq3GFL5SOubW6ewfqvoS1FouXMoeRgR+jc1Au2BaxlYQ4KBBb+r1ZOW7a5ZbRmE/1kRBLKyaMmc9BrbSbPnaP+qAyg/OtmX9akGfPyXs6o="
  file:
  - "package/do-not-merge-wip-for-github.zip"
  on:
    repo: sanemat/do-not-merge-wip-for-github
    tags: true
  skip_cleanup: true
