language: node_js
sudo: false
node_js:
  - 'node'
notifications:
  email:
  - ogataken@gmail.com
after_success:
- bin/build.sh
deploy:
  provider: releases
  api_key:
    secure: "LjK0UJCHn3UP3D6DMbVSGI8FAv5Sud6mA8gn4SUm33yI9yDy6Qr3215fxnxch4fdewn4HMoXx/RFHN9ADnfI0NyOT/sfaH+M4NZG85Sp7cogA3nLTMZRHxWGZaZQO3nF6XKmd9MzLwy7cx418TdjEHXJ0ciFxFPdh5OWSrv6o08="
  file:
  - "package/do-not-merge-wip-for-github.zip"
  on:
    repo: sanemat/do-not-merge-wip-for-github
    tags: true
  skip_cleanup: true
