language: node_js
sudo: false
node_js:
  - '6'
before_install:
  - rvm install 2.3.1
  - gem install compass
notifications:
  email:
  - ogataken@gmail.com
after_success:
- bin/build.sh
deploy:
  provider: releases
  api_key:
    secure: "ElYRf446v/Yt+k6KIjSHhMA4WvVtS3AeM6lmZZyJ75AE+5L9HrVdA2Gdpw225wZlVRt9G0G7X5rfpOFVwWU3nOvR9hN1haCMdAmnxOtYIqqopk/A+/+ALJOuul0kXXw0fHDqNGL73xen5O0UkZeJz6DuUTwBbPCPV78zZrYOAAs="
  file:
  - "package/do-not-merge-wip-for-github.zip"
  on:
    repo: sanemat/do-not-merge-wip-for-github
    tags: true
  skip_cleanup: true
